receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: "localhost:4317"
    tls:
      insecure: true
  otlphttp/rootpilot:
    endpoint: "http://otel-adapter-service:8004"
    tls:
      insecure: true
    encoding: protobuf

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/rootpilot]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/rootpilot]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/rootpilot]
